### ISSUE TITLE
Fix comment design

### ISSUE THREAD

**Issue by gnunicorn** [TeamFranka/affinity#61]
Comments are ugly right now. Let's move to a Stackoverflow style system, where the first layer of comments has a prominent style, the second is inlined (and no others below exist), similarly as in this mockup:

![image](https://user-images.githubusercontent.com/40496/109815507-00492480-7c30-11eb-8fa8-5bee2e47faa4.png)

Maybe we can still have likes and reactions on the second level but also inline them behind the entry.

To fix this, please also provide tests for:
- [ ] commenting,
- [ ] and commenting on a comment as another user
- [ ] liking of the comment, and the comment's comment
- [ ] posting another comment under the post itself

Technically everything is there, this is only about moving them around as needed in the UI and fixing any potential glitches or problems (probably want to drop the usage of `ion-row` and  `ion-col`).

**Comment by zesisu** [comment]
On it!
