### ISSUE TITLE
App rollout

### ISSUE THREAD

**Issue by gnunicorn** [TeamFranka/affinity#70]
How do  we get the packaged App into the hands of the people?

We already have an [appcenter](https://appcenter.ms/) set up for it, but no clear plan how to use that.

**Comment by zesisu** [comment]
We should use it to set up alpha test groups to get the core functionality tested first before dealing with UI and platform-specific things, I guess. At least three important use-cases come to mind:

1. inter-group and intra-group communication
2. general onboarding and community building
3. value-proposition for guest accounts

Getting more information about these three functionalities early on could help us nail it in the long run!

**Comment by gnunicorn** [comment]
This was mainly about the technical issue of packaging, signing, the logistics of getting it to taht alpha team... Do we go over the AppStore?

**Comment by zesisu** [comment]
It may be enough to just have one unofficial version for the Olvenstedt people to download directly. But tbh, the last time I manually installed an unofficial and unregulated app was on my Blackberry many many years ago... Not sure if that is even still possible today. Will leave this question to the pros!
